on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - run: echo All Good

#[actions]
#ENABLED = true
#DEFAULT_ACTIONS_URL = https://code.forgejo.org

#wget -O forgejo-runner https://code.forgejo.org/forgejo/runner/releases/download/v3.3.0/forgejo-runner-3.3.0-linux-
#chmod +x forgejo-runner
#wget -O forgejo-runner.asc https://code.forgejo.org/forgejo/runner/releases/download/v3.3.0/forgejo-runner-3.3.0-linux-amd64.asc
#gpg --keyserver keys.openpgp.org --recv EB114F5E6C0DC2BCDD183550A4B61A2DC5923710
#gpg --verify forgejo-runner.asc forgejo-runner
#docker run --rm code.forgejo.org/forgejo/runner:3.3.0 forgejo-runner --version
